# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  name: 'MegiPC'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install PreEmptive.Protection.Dotfuscator.Pro.Eval -OutputDirectory $(Agent.TempDirectory) -PreRelease -x -Source https://pkgs.dev.azure.com/MegiTeneqexhi/MegiTeneqexhi/_packaging/PreEmptive.Protection.Dotfuscator.Pro/nuget/v3/index.json'
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  env: { "NUGET_RESTORE_MSBUILD_ARGS": '/p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)\PreEmptive.Protection.Dotfuscator.Pro.Eval\tools\msbuilddir"' }

- task: VSBuild@1
  displayName: 'Restore Packages'
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    vsVersion: '16.0'
    msbuildArgs: '/t:Restore /p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)\PreEmptive.Protection.Dotfuscator.Pro.Eval\tools\msbuilddir" /p:DotfuscatorLicense="0E3DA747DF7C4106B645EDCE317C7C78:megi.teneqexhi@univie.ac.at"'
- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)\PreEmptive.Protection.Dotfuscator.Pro.Eval\tools\msbuilddir" /p:DotfuscatorLicense="0E3DA747DF7C4106B645EDCE317C7C78:megi.teneqexhi@univie.ac.at"'
    jdkOption: 'JDKVersion'