# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  name: 'MegiPC'

variables:
 
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install PreEmptive.Protection.Dotfuscator.Pro.Eval -OutputDirectory $(Agent.TempDirectory)\nugetinstall -PreRelease -x -Source https://pkgs.dev.azure.com/MegiTeneqexhi/MegiTeneqexhi/_packaging/Xamarin1/nuget/v3/index.json'
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
  env: { "NUGET_RESTORE_MSBUILD_ARGS": '/p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)\PreEmptive.Protection.Dotfuscator.Pro.Eval\tools\msbuilddir"' }

- task: VSBuild@1

  inputs:

    solution: '**/*.sln'

    msbuildArgs: '/p:DotfuscatorMSBuildDir=$(Build.Repository.LocalPath)\nugetinstall\PreEmptive.Protection.Dotfuscator.Pro.Eval\tools\msbuilddir'

    platform: '$(buildPlatform)'

    configuration: '$(buildConfiguration)'